Task01
itaru-work/kintone_dojo pull request #1
Opened 2022-06-24 09:09 UTC by itaru-work

お疲れ様です！
初めてのプルリクエストなのでうまくできているかが、不安なのですがよろしくお願いします🙇🏻‍♂️
週末に送ってしまい、申し訳ないです。。。

2022-06-27 03:36 UTC, saek-0 requested changes
task1おつかれさま！
CSSのインデントと
4つの画像のclassに部分についてコメント書いたので、
修正して再提出お願いします！

2022-06-27 03:36 UTC, saek-0 commented on task1/task1.css
> +* {
全体的にCSSのインデントが不自然なので修正しましょう！

2022-06-27 03:36 UTC, saek-0 commented on task1/task1.html
> +      <div class="center">
4製品の画像にdivでcenterクラスを付与してますが、
その親divにクラスを2つ付与する、もしくはimgタグにstyleで付与する方法で記載をしてみてください！

L24, L29, L34 も同様です

2022-06-28 13:27 UTC, saek-0 requested changes
コメントの確認お願いします！
インデントに関しては、vscodeの設定かな？
https://qiita.com/pyon_kiti_jp/items/031de3fdd3c60ddc21bc

2022-06-28 13:27 UTC, saek-0 commented on task1/task1.css
> +	text-align: center;
この`width: 100%;   text-align: center;`は共通化できそう。
共通するstyleをまとめてみてください！
ヒント：htmlの方のコメント見てみてください

2022-06-28 13:27 UTC, saek-0 commented on task1/task1.html
> +      <img src="./img/image-kn.png" alt="kintone" class="product">
`div class="center"`消してくれたと思うんだけど、
実は親divにクラス名を複数指定できます。
https://shu-sait.com/html-class-fukusuu/

`div class="kintone center"`で書いてみてください！

2022-06-29 02:46 UTC, itaru-work commented
お忙しい中レビューありがとうございます！
インデントの設定もいただいたリンクを参考に変更できました！
styleも共通しているところをcenterというクラス名にまとめました。
再度チェックお願いします🙇🏻‍♂️

2022-06-29 05:09 UTC, saek-0 approved these changes
OKです！task1おつかれさまです 🎉

2022-06-29 05:11 UTC, merged