Task02
itaru-work/kintone_dojo pull request #2
Opened 2022-06-29 00:05 UTC by itaru-work

芦田さんお疲れ様です！
task2(3)のJSのオブジェクトに関する課題が完了したので、レビューお願い致します🙇🏻‍♂️
変数の名前の付け方がすごい曖昧なのものになっていて申し訳ないです。。。
お忙しいところ恐縮ですが、よろしくお願いします！

2022-07-01 00:39 UTC, saek-0 requested changes
手順3-3にコメントしたので確認お願いします！

2022-07-01 00:39 UTC, saek-0 commented on task2/task3.html
> +      li.textContent = folderObject.folderName;
手順3-3の閲覧権限がeveryoneのものは、
Object.keys(fileManage)内で判定できるので、手順3-2の中に入れ込めばさらにコードが短くなると思います！
修正してみてください！

2022-07-01 00:39 UTC, saek-0 commented on task2/task3.html
> +  })
`;` 忘れないようにしましょう

2022-07-01 06:37 UTC, itaru-work commented
お忙しい中レビューありがとうございます！
一応コード量を減らしてみたつもりなのですが、もしまだ至らない点あれば指摘いただけると幸いです🙇🏻‍♂️

2022-07-01 07:40 UTC, saek-0 requested changes
最後に一点！さらにコードを短くする術を。
細かいですが、修正して提出お願いします_(..)！

2022-07-01 07:40 UTC, saek-0 commented on task2/task3.html
> +const folderKeys = Object.keys(fileManage);
const folderKeys = Object.keys(fileManage);で変数宣言しているけど1回しか使われていないので変数に入れない方がコード量を減らせると思います。
それで、Object.keys(fileManage)をforEachで回せば、
そのあとの128行目のforEachを、Object.keys(fileManage[val]).forEach((v)にすることができるので、125,126行の変数宣言も要らなくなるかと。
※手順3-3の変数とかは修正する必要があります

2022-07-04 04:16 UTC, itaru-work commented
レビューありがとうございます！
確かに1回しか変数を使用していない箇所は、変数にわざわざ落とし込まない方がコード量が少なくなりますね🤔
勉強になりました🙇🏻‍♂️
指摘いただいたところを変更したので、ご確認お願い致します。

2022-07-05 00:11 UTC, saek-0 commented on task2/task3.html
> +const folderKeys = Object.keys(fileManage);
@itaru-work 
修正コード確認しました！
概ねokですが、L120`const folderKeys = Object.keys(fileManage);` は消し忘れかな？`
 修正して再コミットしてくれればokです！

2022-07-05 07:50 UTC, saek-0 requested changes
修正コード確認しました！
概ねokですが、L120 `const folderKeys = Object.keys(fileManage); ` は消し忘れかな？`

修正して再コミットしてくれればokです！

2022-07-05 09:18 UTC, itaru-work commented
遅くなってすみません💦
120行目は自分の見落としでした。再度チェックお願いします🙇🏻‍♂️

2022-07-06 02:15 UTC, saek-0 approved these changes
OKです！🎉
コメントの部分、手順xだけではなくて具体的に何をやっているか書くとわかりやすそうです！次課題出す時から気をつけてみてください！

2022-07-06 02:51 UTC, itaru-work commented
承知しました！
以後意識的に内容を書き出してみます！

2022-07-11 02:15 UTC, saek-0 commented
@itaru-work 
task02がコンフリクトしててマージできないので、
変更してもらってもいいですか？
たぶんこれ 
https://qiita.com/te2u/items/c23f82ec84cf65564554

2022-07-11 05:50 UTC, merged