中間課題
itaru-work/kintone_dojo pull request #4
Opened 2022-07-05 09:19 UTC by itaru-work

お疲れ様です！
ここからレビュー依頼が立て続けになるかもしれないので申し訳ないのですが、よろしくお願いします🙇🏻‍♂️

2022-07-13 02:39 UTC, saek-0 requested changes
コメントの確認お願いします！

実はテーブルの作成はinnerHTMLを使うとコードを短縮できます。
変数で定義したhtml要素に、テーブル情報を加算代入してあげるイメージです。
余裕があったらそちらの書き変えてみてください。

2022-07-13 02:39 UTC, saek-0 commented on 中間課題/main.js
> +    for (let i = 0; i < newsArray.length; i++) {
forEachを使いましょう。
forEachは要素数文処理を行いたい時に使われて、今回も要素数分処理を行いたい場合に当てはまるので適切だと思います！
for文は例えばページネーションなんかに使われます。100件データ取得されたけど、1ページ20件ずつ表示したい時なんかはfor文で数を決めて処理を行うことがあります。
kintoneにおいてはあまり使われることはないのでforEachを使って記述してみてください。

2022-07-13 02:39 UTC, saek-0 commented on 中間課題/main.js
> +      }
CSSの要素は、CSS要素に入れてあげたいですね

2022-07-14 02:25 UTC, itaru-work commented
お疲れ様です！指摘いただいた以下の3点を変更したので、ご確認お願い致します🙇🏻‍♂️
・テーブルをinnerHTMLを使用して作成
・for文からforEach文へ変更
・JSに書いていたCSSの記載を削除

2022-07-14 02:49 UTC, saek-0 approved these changes
LGTMです！🎉
Dojoの課題おつかれさまでした！(レビュー溜めてしまって申し訳なかったです！

瀧井くんは課題の意味を汲み取ってちゃんとコードに落とし込めていて、
レビューに対しても、理想通りのコードでプルリクが来ることが多く感心しておりました。
Dojoで学んだことはどの部署でも役に立つはずです。
引き続き、研修課題の方も頑張ってください！

2022-07-14 02:49 UTC, merged

2022-07-14 04:14 UTC, itaru-work commented
とんでもないです！SE-Dの方最近どの方も忙しそうですよね...
お忙しい中レビューしていただきありがとうございました🙌🏻
不明点を毎回レビューで丁寧に教えていただいていたおかげです！
教えていただいたことを糧に頑張ります💪🏻