Task06
itaru-work/kintone_dojo pull request #5
Opened 2022-07-05 09:21 UTC by itaru-work

お疲れ様です！
お手隙の際にレビューしていただけると幸いです🙇🏻‍♂️
よろしくお願い致します！

2022-07-06 08:58 UTC, saek-0 requested changes
コメントしました！
確認お願いします

2022-07-06 08:58 UTC, saek-0 commented on task6/task6.js
> +            type: "DROP_DOWN",
ダブルクォートでもいいですが、L20とL24の囲み方と合わせた方が個人的に良いと思います

2022-07-06 08:58 UTC, saek-0 commented on task6/task6.js
> +            type: 'CHECK_BOX',
細かいですが、
```suggestion
          '状況': {
            type: 'CHECK_BOX',
```

2022-07-06 08:58 UTC, saek-0 commented on task6/task6.js
> +            type: 'MULTI_LINE_TEXT',
```suggestion
          '課題': {
            type: 'MULTI_LINE_TEXT',
```

2022-07-06 08:58 UTC, saek-0 commented on task6/task6.js
> +    };
こっちのセミコロンはいらなそうです

2022-07-07 02:08 UTC, itaru-work commented
レビューありがとうございます！
指摘いただいた箇所を直して、再度pushしたのでご確認お願いします🙇🏻‍♂️

2022-07-07 07:24 UTC, saek-0 requested changes
配列に対してはforEachのほうが推奨でした！
修正してみてください。

2022-07-07 07:24 UTC, saek-0 commented on task6/task6.js
>        event.record.Table.value.push({
L12 〜
配列に対してはforよりforEach推奨なので、forEachの方で記述してみてください！

2022-07-11 01:15 UTC, itaru-work commented
遅くなってすみません💦
forEachへ書き換えをして、挙動も正常に動くことを確かめました！
レビィーお願い致します🙇🏻‍♂️

2022-07-11 02:14 UTC, saek-0 approved these changes
OKです！
task6おつかれさまでした！

2022-07-11 02:14 UTC, merged