Task07
itaru-work/kintone_dojo pull request #6
Opened 2022-07-06 07:22 UTC by itaru-work

お疲れ様です！
お忙しいところ恐縮なのですが、レビューお願い致します🙇🏻‍♂️

2022-07-11 04:14 UTC, saek-0 requested changes
回答お疲れさま！(レビュー溜めてしまった申し訳ないです)

コメントしたので確認お願いします！
task07もコンフリクトしちゃっているので、修正お願いします

2022-07-11 04:14 UTC, saek-0 commented on task7/task7.js
> +    console.log(event); // 確認用
console.logはデバッグ用なのでプルリクする際には削除しましょう！

2022-07-11 04:14 UTC, saek-0 commented on task7/task7.js
> +    'app.record.create.change.管理番号', 'app.record.edit.change.管理番号'], (event) => {
イベントを繋げて書くと、あとで見返しずらいので下記に書き換えるとgoodです

kintone.events.on([
    'app.record.create.change.日付',
    'app.record.edit.change.日付',
    'app.record.create.change.サイボウズ製品',
    'app.record.edit.change.サイボウズ製品',
    'app.record.create.change.管理番号',
    'app.record.edit.change.管理番号',
  ], (event) => {

2022-07-11 04:14 UTC, saek-0 commented on task7/task7.js
> +    date = date.replace('-', '');
課題文は、「日付操作にはdate-fnsライブラリを利用する」という指定があったはずです！
書き換えお願いします

2022-07-11 10:27 UTC, itaru-work commented
dateFnsライブラリの箇所など諸々変更しました。
お忙しいところ恐縮ですが、再度レビューお願い致します🙇🏻‍♂️

2022-07-12 00:36 UTC, saek-0 requested changes
修正OKです！

あと、課題文見ると編集不可にするタイミングはフィールドが変更されたときではなく、レコードの追加/編集画面が開かれた時と指定があったので、そこだけ別イベント用意して記載してください！

2022-07-12 00:36 UTC, saek-0 commented on task7/task7.js
> +    event.record['重複禁止項目_文字列'].disabled = true;
課題は、編集不可にするタイミングはフィールドが変更されたときではなく、
レコードの追加/編集画面が開かれたときと指定があったので、別のイベントを用意してそちらに記載しましょう！

2022-07-12 01:34 UTC, itaru-work commented
編集不可にするタイミングについては失念していました💦
変更したので、ご確認お願い致します。

2022-07-12 01:40 UTC, saek-0 approved these changes
OKです！

2022-07-12 01:40 UTC, merged