Task09
itaru-work/kintone_dojo pull request #8
Opened 2022-07-07 01:49 UTC by itaru-work

お疲れ様です！
タスク9が完了したのですが、課題のPDFに書いてあった「イベントハンドラーに対して、falseをreturnすると保存処理をキャンセルできる」という処理が以下のサイトを見て試してみてもうまくいかなかったので、別の方法で試しています。(リンク長くなります💦)
https://developer.cybozu.io/hc/ja/articles/202166270-%E3%83%AC%E3%82%B3%E3%83%BC%E3%83%89%E7%B7%A8%E9%9B%86%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88#:~:text=%E3%83%AC%E3%82%B3%E3%83%BC%E3%83%89%E7%B7%A8%E9%9B%86%E7%94%BB%E9%9D%A2%E3%81%AE%E4%BF%9D%E5%AD%98%E5%AE%9F%E8%A1%8C%E5%89%8D%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88,-PC%E3%81%A8%E3%83%A2%E3%83%90%E3%82%A4%E3%83%AB&text=false%E3%82%92return%E3%81%99%E3%82%8B%E3%81%A8%E4%BF%9D%E5%AD%98,%E5%87%A6%E7%90%86%E3%82%92%E3%82%AD%E3%83%A3%E3%83%B3%E3%82%BB%E3%83%AB%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%80%82
その点も何かアドバイスいただけると幸いです！よろしくお願い致します🙇🏻‍♂️

2022-07-12 00:38 UTC, itaru-work commented
お疲れ様です！
レビューをもし始められていたら申し訳ないのですが、以前のバージョンからクエリを使用したものに変更しました💦
その点ご理解いただけますと幸いです🙇🏻‍♂️よろしくお願いします！

2022-07-13 01:42 UTC, saek-0 requested changes
コメントの確認お願いします！
追加と編集で既存レコード数の処理が分けられているかがポイントです。
クエリを書き分けてあげましょう。

2022-07-13 01:42 UTC, saek-0 commented on task9/task9.js
> +    const query = '重複禁止項目 = "' + uniqueKey + '"';
新規レコード追加の場合は
const query = '重複禁止項目 = "' + uniqueKey + '"';
このクエリーで0件になったら重複レコードなしとして判断されますが、
既存レコード編集だった場合の処理が抜けてます。

const query = '重複禁止項目 = "' + uniqueKey + '"';
これだけだとレコード編集時にすでにDBには1件入っているので、GETしたらlengthが1で取れてくると思います。
その場合はレコード番号が今開いているレコード番号と同じでなければ重複していないという処理を入れてあげましょう！

2022-07-13 02:16 UTC, itaru-work commented on task9/task9.js
> +    const query = '重複禁止項目 = "' + uniqueKey + '"';
確かにそうですね🤔
ご指摘ありがとうございます！自分では気づかなかった点なので助かります！
pushしたら再度連絡します！

2022-07-13 05:48 UTC, itaru-work commented
お疲れ様です！
コード自体は動くのは動くのですが、JSwatchdogにかけたときに26行目のelseが不要だと指摘されます。
ただ、このelseを外すと前に付け加えたif文(24~26行まで)を保持した状態でも、元のコードの挙動と同じになってしまい、八方塞がりな状態です。
対応策としてはレコード作成時と編集時でイベントを分けるべきなのかなとも思っているのですが、どのように結論を持っていけばよいでしょうか？お忙しいところ恐縮ですが、レビューよろしくお願いします🙇🏻‍♂️

2022-07-13 08:48 UTC, saek-0 commented on task9/task9.js
> +        } else {
if文で条件式に合致した場合はreturnされるので、その後の処理は実行されない、要するにelse にいらないよ〜という意味のエラーですね。
elseはずして、L37のreturn eventを適切な位置に変更してあげれば意図した挙動になるはずです！(手元で確認できました

2022-07-13 23:43 UTC, itaru-work commented
おはようございます！
昨日詰まっていた点に関しては20行目の条件式のところで変数の型が違うが故に自分の意図しない挙動になっていたので、elseを外しつつ、その点を修正しました。(挙動もうまくいきました。)
芦田さんにアドバイスいただいたelseを外して、return eventの位置を変えるという方法は昨日も結構考えていたのですが、分かりませんでした💦

2022-07-14 01:52 UTC, merged